export const QueryKey = {
  BOOKS: "BOOKS",
  CATEGORIES: "CATEGORIES",
  AUTHORS: "AUTHORS",
  USERS: "USERS",
  DATEBORROWS: "DATEBORROWS",
  BORROWITEMS: "BORROWITEMS",
  COMMENTS: "COMMENTS",
};
